# Generated by Django 3.0.7 on 2022-03-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20220106_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batsman',
            name='match',
        ),
        migrations.RemoveField(
            model_name='batsman',
            name='player',
        ),
        migrations.RemoveField(
            model_name='batsman',
            name='team',
        ),
        migrations.RemoveField(
            model_name='bowler',
            name='match',
        ),
        migrations.RemoveField(
            model_name='bowler',
            name='player',
        ),
        migrations.RemoveField(
            model_name='bowler',
            name='team',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='match',
        ),
        migrations.RemoveField(
            model_name='commentator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pointstable',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='adminmail',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='adminpass',
        ),
        migrations.AddField(
            model_name='admins',
            name='article',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='admins',
            name='title',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Batsman',
        ),
        migrations.DeleteModel(
            name='Bowler',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Commentator',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='pointstable',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
