# Generated by Django 3.0.7 on 2022-03-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20220301_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='image',
            field=models.FileField(blank=True, default='', max_length=10000, null=True, upload_to=''),
        ),
    ]
