# Generated by Django 4.0.3 on 2022-03-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_admins_photolink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='image',
        ),
    ]
