# Generated by Django 3.0.7 on 2022-03-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_remove_admins_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
